# Basic
title: Yulv
subtitle: GitHub Pages
description: Welcome to my website!
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Yulv
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: CV / Medical Image Computing
url: "https://Yulv-git.github.io"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
    livere: MTAyMC81NjI2MS8zMjcyNA  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    # weibo: 5366874726
    github: Yulv-git
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    mail: yulvchi@qq.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 84f261e25fe54d305ec84561b1d66634

# # Google Analytics
# # ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#     id: UA-84134159-3  
#     host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Homepage

# Navigation buttons in the front page.s
nav:
    - {title: Archives, description: archives, url: '/archive'}
    - {title: Tags, description: tags, url: '/tags'}
    - {title: About, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
